### ISSUE TITLE
Videos are not playing

### ISSUE THREAD

**Issue by aandrew-me** [nxjosephofficial/rumble-desktop-app#1]
Interesting idea of making a desktop app. However I was unable to play videos. There weren't any logs which I could share. 
I was using AppImage

![image](https://user-images.githubusercontent.com/66430340/199893332-f40ad032-7388-453c-9a52-75d43a9086f6.png)

**Comment by nxjosephofficial** [comment]
I didn't test AppImage version but deb version. Video playing in deb version is working for me.
I ran AppImage to get logs and here are logs.
```
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:1795): GLib-GObject-WARNING **: 11:59:19.488: invalid (NULL) pointer instance

(WebKitWebProcess:1795): GLib-GObject-CRITICAL **: 11:59:19.488: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
